#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch FITS cutout maker.
produces FITS cutouts.  The cutouts retain a consistent WCS solution and copy a
subset of the original header keywords.  A photometric zeropoint and its
uncertainty can optionally be injected into the output header.
"""

import argparse
import os
import sys
from typing import Iterable, Sequence, Tuple, Union

from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.nddata import Cutout2D
from astropy import wcs

Number = Union[int, float]
SizeInput = Union[Number, Sequence[Number], Iterable[Number]]


def _check_wcs_simple(hdr, data, ra_deg: float, dec_deg: float) -> Tuple[bool, str]:
    """Replicated from ``make_thumbnails_batch`` to sanity-check the WCS."""

    required = ("CTYPE1", "CTYPE2", "CRVAL1", "CRVAL2", "CRPIX1", "CRPIX2")
    missing = [k for k in required if hdr.get(k) is None]
    if missing:
        return (False, f"Missing WCS keywords: {', '.join(missing)}")

    try:
        world_cs = wcs.WCS(hdr)
    except Exception as exc:  # pragma: no cover - defensive
        return (False, f"WCS construction failed: {exc}")

    try:
        sc = SkyCoord(ra_deg * u.deg, dec_deg * u.deg, frame="icrs")
        xpix, ypix = world_cs.world_to_pixel(sc)
    except Exception as exc:  # pragma: no cover - defensive
        return (False, f"WCS world_to_pixel failed: {exc}")

    if data is None or getattr(data, "ndim", 0) < 2:
        return (False, "Image data is empty or not 2D.")

    ny, nx = data.shape[0], data.shape[1]
    inside = (0 <= xpix < nx) and (0 <= ypix < ny)
    if not inside:
        return (
            False,
            f"Target outside image bounds: x={xpix:.1f}, y={ypix:.1f}, size=({nx},{ny})",
        )

    return (True, "OK")


def _normalise_size(size: SizeInput) -> Union[int, Tuple[int, int]]:
    """Convert CLI size inputs to values understood by :class:`Cutout2D`."""

    if isinstance(size, (int, float)):
        return int(round(size))

    if isinstance(size, (tuple, list)):
        if len(size) != 2:
            raise ValueError("Non-scalar size must contain exactly two elements (width, height).")
        return int(round(size[1])), int(round(size[0]))  # Cutout2D expects (ny, nx)

    seq = list(size)
    if len(seq) != 2:
        raise ValueError("Non-scalar size must contain exactly two elements (width, height).")
    return int(round(seq[1])), int(round(seq[0]))


def _prepare_cutout_header(
    src_header: fits.Header,
    cutout: Cutout2D,
    image_path: str,
    ra_deg: float,
    dec_deg: float,
    zeropoint: Number = None,
    zeropoint_unc: Number = None,
) -> fits.Header:
    """Build a FITS header for the cutout with updated WCS metadata."""

    new_header = fits.Header()
    skip = {
        "SIMPLE",
        "BITPIX",
        "NAXIS",
        "NAXIS1",
        "NAXIS2",
        "XTENSION",
        "PCOUNT",
        "GCOUNT",
        "THEAP",
        "TFIELDS",
    }

    for card in src_header.cards:
        key = card.keyword
        if not key or key in skip or key.startswith("NAXIS"):
            continue
        # The WCS keywords will be refreshed from the cutout; avoid duplicating them now.
        if key.startswith("CD") or key.startswith("PC") or key.startswith("CDELT"):
            continue
        if key in ("CRPIX1", "CRPIX2", "CRVAL1", "CRVAL2", "CTYPE1", "CTYPE2", "CUNIT1", "CUNIT2"):
            continue
        new_header.append(card, end=True)

    # Inject fresh WCS solution for the cutout
    wcs_header = cutout.wcs.to_header(relax=True)
    for key, value in wcs_header.items():
        new_header[key] = value

    ny, nx = cutout.data.shape
    new_header["NAXIS"] = 2
    new_header["NAXIS1"] = nx
    new_header["NAXIS2"] = ny

    new_header["ORIGFILE"] = (os.path.basename(image_path), "Source FITS image")
    new_header["CUT_RA"] = (float(ra_deg), "Cutout centre RA (deg)")
    new_header["CUT_DEC"] = (float(dec_deg), "Cutout centre Dec (deg)")
    new_header["CUTW"] = (nx, "Cutout width in pixels")
    new_header["CUTH"] = (ny, "Cutout height in pixels")

    if zeropoint is not None:
        new_header["ZEROPT"] = (float(zeropoint), "Photometric zero point")
    if zeropoint_unc is not None:
        new_header["ZPTERR"] = (float(zeropoint_unc), "Photometric zero point uncertainty")

    new_header.add_history("FITS cutout generated by make_fits_cutouts_batch.py")
    return new_header


def make_fits_cutout(
    image_path: str,
    ra_deg: Number,
    dec_deg: Number,
    size_px: SizeInput,
    outdir: str,
    *,
    zeropoint: Number = None,
    zeropoint_unc: Number = None,
    hdu_index: int = 1,
    overwrite: bool = False,
    mode: str = "partial",
    fill_value: Number = float("nan"),
) -> str:
    """
    Generate a FITS cutout centred on ``(ra_deg, dec_deg)``.

    Parameters mirror :func:`make_thumbnail` but the output is a FITS file that
    contains correct WCS metadata and optional zeropoint keywords.
    """

    ra_deg = float(ra_deg)
    dec_deg = float(dec_deg)

    # Ensure output directory exists before heavy lifting
    os.makedirs(outdir, exist_ok=True)

    position = SkyCoord(ra_deg * u.deg, dec_deg * u.deg, frame="icrs")
    size = _normalise_size(size_px)

    with fits.open(image_path, memmap=True) as hdul:
        if hdu_index >= len(hdul):
            raise RuntimeError(
                f"Requested HDU index {hdu_index}, but file '{image_path}' only has {len(hdul)} HDU(s)."
            )
        hdu = hdul[hdu_index]
        data = hdu.data
        header = hdu.header

        ok, message = _check_wcs_simple(header, data, ra_deg, dec_deg)
        if not ok:
            raise RuntimeError(f"WCS check failed: {message}")

        image_wcs = wcs.WCS(header)
        cutout = Cutout2D(
            data,
            position,
            size,
            wcs=image_wcs,
            mode=mode,
            fill_value=fill_value,
        )

        output_header = _prepare_cutout_header(
            header,
            cutout,
            image_path,
            ra_deg,
            dec_deg,
            zeropoint,
            zeropoint_unc,
        )

        runid = os.path.splitext(os.path.basename(image_path))[0]
        ra_tag = f"{ra_deg:.5f}".replace(".", "p")
        dec_tag = f"{dec_deg:.5f}".replace(".", "p")
        outname = f"{runid}_{ra_tag}_{dec_tag}.fits"
        outpath = os.path.join(outdir, outname)

        primary_hdu = fits.PrimaryHDU(data=cutout.data, header=output_header)
        fits.HDUList([primary_hdu]).writeto(outpath, overwrite=overwrite)

    return outpath


def _parse_args():
    parser = argparse.ArgumentParser(
        description="Create FITS cutouts with preserved WCS metadata (uses HDU[1] by default)."
    )
    parser.add_argument("--ra", required=True, type=float, help="ICRS RA in degrees (applied to all images)")
    parser.add_argument("--dec", required=True, type=float, help="ICRS Dec in degrees (applied to all images)")
    parser.add_argument(
        "--size",
        type=float,
        default=None,
        help="Square cutout size in pixels. Provide --width/--height for rectangular cutouts.",
    )
    parser.add_argument("--width", type=float, default=None, help="Cutout width in pixels (overrides --size if set)")
    parser.add_argument("--height", type=float, default=None, help="Cutout height in pixels (overrides --size if set)")
    parser.add_argument("--outdir", required=True, help="Directory to save FITS cutouts")
    parser.add_argument("images", nargs="+", help="One or more FITS image paths")
    parser.add_argument(
        "--zeropoint",
        type=float,
        default=None,
        help="Photometric zeropoint to inject into the output header",
    )
    parser.add_argument(
        "--zeropoint-unc",
        type=float,
        default=None,
        help="Uncertainty of the photometric zeropoint (written as ZPTERR)",
    )
    parser.add_argument(
        "--hdu",
        type=int,
        default=1,
        help="FITS HDU index to cut (default: 1)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files",
    )
    parser.add_argument(
        "--mode",
        choices=("trim", "partial", "strict"),
        default="partial",
        help="Cutout2D mode handling edges (default: partial)",
    )
    parser.add_argument(
        "--fill-value",
        type=float,
        default=float("nan"),
        help="Fill value for pixels falling outside the input image (used with --mode partial)",
    )
    return parser.parse_args()


def main():
    args = _parse_args()

    if args.width is not None or args.height is not None:
        if args.width is None or args.height is None:
            raise SystemExit("Both --width and --height must be provided for rectangular cutouts.")
        size = (args.width, args.height)
    else:
        if args.size is None:
            raise SystemExit("Please provide --size or both --width/--height.")
        size = args.size

    successes = []
    failures = []

    for img in args.images:
        try:
            outp = make_fits_cutout(
                img,
                args.ra,
                args.dec,
                size,
                args.outdir,
                zeropoint=args.zeropoint,
                zeropoint_unc=args.zeropoint_unc,
                hdu_index=args.hdu,
                overwrite=args.overwrite,
                mode=args.mode,
                fill_value=args.fill_value,
            )
            print(f"[OK] {img} -> {outp}")
            successes.append(outp)
        except Exception as exc:  # pragma: no cover - CLI error handling
            print(f"[ERROR] {img}: {exc}", file=sys.stderr)
            failures.append((img, str(exc)))

    if successes:
        print(
            f"Completed: {len(successes)} succeeded, {len(failures)} failed. Output dir: {args.outdir}"
        )
        sys.exit(0)

    print(f"All failed: {len(failures)} images.", file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()